version: '3.8'

services:
  db:
    image: postgres
    container_name: evaluat
    environment:
      POSTGRES_USER: evaluat-adm
      POSTGRES_PASSWORD: 910f4444bb75187fcbc4ba493281a15b
      POSTGRES_DB: postgres

    ports:
      - "5432:5432"
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d
    networks:
      - evaluat_network

networks:
  evaluat_network:
    driver: bridge

#  psql -U evaluat-adm -d postgres