version: '3.8'

services:
    db:
        env_file: .env
        image: postgres
        container_name: evaluat-db
        ports:
            - '5432:5432'
        volumes:
            - ./sql-scripts:/docker-entrypoint-initdb.d
        networks:
            - evaluat_network
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB -h localhost"]
            interval: 10s
            timeout: 5s
            retries: 5

    app:
        image: evaluat
        container_name: evaluat-app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
            - '9222:9222'
        depends_on:
            db:
                condition: service_healthy
        volumes:
            - ./src:/usr/app/src
        networks:
            - evaluat_network
        command: npm run dev

networks:
    evaluat_network:
        driver: bridge
#  psql -U evaluat-adm -d evaluat
