version: '3.8'

services:
    db:
        env_file: .env
        image: postgres
        container_name: evaluat-db
        ports:
            - '5432:5432'
        volumes:
            - ./sql-scripts:/docker-entrypoint-initdb.d
        networks:
            - evaluat_network

    app:
        image: evaluat
        container_name: evaluat-app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
            - '9222:9222'
        depends_on:
            - db
        volumes:
            - ./src:/usr/app/src
        networks:
            - evaluat_network
        command: npm run dev

networks:
    evaluat_network:
        driver: bridge
#  psql -U evaluat-adm -d evaluat
